package com.bookStation.models.model;

public enum ProcessEnum {

    ADD_BOOK,UPDATE_BOOK,DELETE_BOOK,LIST_ALL_BOOKS,

    CREATE_PUBLISHER,UPDATE_PUBLISHER,DELETE_PUBLISHER,LIST_ALL_PUBLISHERS,

    CREATE_AUTHOR,UPDATE_AUTHOR,DELETE_AUTHOR,LIST_ALL_AUTHOR,

    CREATE_GROUP,UPDATE_GROUP,ADD_USER_TO_GROUP,DELETE_GROUP,LIST_ALL_GROUP,

    ADD_EMPLOYEE,DELETE_EMPLOYEE,LIST_ALL_EMPLOYEES,

    ADD_NEW_PERMISSION_RULE,DROP_PERMISSION_RULE,

    ADD_NEW_CATEGORY,UPDATE_CATEGORY,DELETE_CATEGORY,LIST_ALL_CATEGORY,

    APPROVE_RESERVATION,REJECT_RESERVATION,SHOW_RESERVATIONS_REQUEST,

    CREATE_LIBRARY,DELETE_LIBRARY,UPDATE_LIBRARY_INFO,LIST_ALL_LIBRARIES,

    LIST_LIVE_SESSIONS
}
